application: gpluscommutetracker
version: alpha1
runtime: python27
api_version: alpha1
threadsafe: true

handlers:
- url: /.*
  script: gpluscommutetracker.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest